# Generated by Django 5.0.4 on 2024-04-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
