# Generated by Django 5.0.4 on 2024-04-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0002_student_birthdate_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
