# Generated by Django 5.0.4 on 2024-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0004_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
