# Generated by Django 5.0.4 on 2024-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0015_remove_result_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='testkey',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
