# Generated by Django 5.0.4 on 2024-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0016_answerkey_subject_testkey_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkey',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testkey',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
