# Generated by Django 5.0.4 on 2024-05-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0022_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
