# Generated by Django 5.0.4 on 2024-05-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0023_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
