# Generated by Django 5.0.4 on 2024-05-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0026_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
