# Generated by Django 5.0.4 on 2025-01-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0027_testkey_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testkey',
            name='image',
        ),
        migrations.AddField(
            model_name='testkey',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
