# Generated by Django 5.0.4 on 2025-01-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0028_remove_testkey_image_testkey_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testkey',
            name='images',
        ),
        migrations.AddField(
            model_name='testkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
