# Generated by Django 5.0.4 on 2025-01-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0029_remove_testkey_images_testkey_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testkey',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
