# Generated by Django 5.0.4 on 2025-01-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0030_alter_testkey_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testkey',
            name='image',
        ),
    ]
