# Generated by Django 5.0.4 on 2025-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0031_remove_testkey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
