# Generated by Django 3.2 on 2025-10-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0033_result_is_submitted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('subject', 'question_text', 'image')},
        ),
    ]
