# Generated by Django 3.2 on 2025-10-28 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0034_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='situation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='situation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
