# Generated by Django 3.2 on 2025-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0036_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.JSONField(default=list, help_text='Select one or more courses'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
