# Generated by Django 3.2 on 2025-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0037_auto_20251028_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='situation_image',
            field=models.ImageField(blank=True, null=True, upload_to='situation_images/'),
        ),
    ]
