# Generated by Django 3.2 on 2025-10-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0038_question_situation_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_uuid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='situation_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='situation_image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='situation_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
