# Generated by Django 3.2 on 2025-10-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0039_auto_20251029_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='board_exam',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics & Communications Engineering', 'Electronics & Communications Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.CharField(choices=[('BSCE', 'BSCE'), ('BSEE', 'BSEE'), ('BSECE', 'BSECE'), ('BSME', 'BSME'), ('General Engineering', 'General Engineering')], default='General Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='level_of_difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Misc', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
