# Generated by Django 3.2 on 2025-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0040_auto_20251030_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddField(
            model_name='question',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
