# Generated by Django 3.2 on 2025-11-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0041_auto_20251030_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='board_exam',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='topic',
            field=models.CharField(default='Misc', max_length=100),
        ),
        migrations.AddField(
            model_name='testkey',
            name='board_exam',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='testkey',
            name='topic',
            field=models.CharField(default='Misc', max_length=255),
        ),
    ]
