# Generated by Django 3.2 on 2025-11-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0042_auto_20251105_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerkey',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='testkey',
            name='topic',
        ),
    ]
