# Generated by Django 3.2 on 2025-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0043_auto_20251105_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkey',
            name='board_exam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testkey',
            name='board_exam',
            field=models.CharField(max_length=50),
        ),
    ]
