# Generated by Django 3.2 on 2025-11-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0045_result_total_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(unique=True)),
                ('board_exam', models.CharField(max_length=50)),
                ('total_items', models.IntegerField()),
                ('score', models.IntegerField()),
                ('percent', models.FloatField()),
                ('total_time', models.FloatField(help_text='Total time in seconds')),
                ('answers', models.JSONField(help_text="List of student's answers with question_id, selected, correct, time_spent")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
