# Generated by Django 3.2 on 2025-11-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0048_alter_result_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
    ]
