# Generated by Django 3.2 on 2025-11-18 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0049_alter_question_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('total_items_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('average_time_per_item', models.FloatField(default=0.0)),
                ('last_practice_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('board_exam', models.CharField(max_length=50)),
                ('total_items_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('average_time_per_item', models.FloatField(default=0.0)),
                ('last_practice_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DifficultyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_exam', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('total_items_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('last_practice_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
