# Generated by Django 3.2 on 2025-11-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0050_difficultyanalytics_subjectanalytics_topicanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='board_exam',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], default='General', max_length=50),
        ),
    ]
